### ISSUE TITLE
Loving this — can Deforum be added?

### ISSUE THREAD

**Issue by JT-Apps** [seia-soto/stable-diffusion-webui-m1#1]
This has been the most stable, foolproof of using Automatic across multiple machines, so thank you. Do you think you could update/add a version specifically for Deforum, a la what this person is doing [here](https://youtu.be/4esuRSyirOk) so it may be run locally? Possible?

**Comment by seia-soto** [comment]
I'm interested. I'll look forward it in few days as it's night currently on my TZ.

**Comment by JT-Apps** [comment]
Thank you! Appreciate that!

**Comment by seia-soto** [comment]
Sorry to say, I looked at that and concluded that the deforum requires Colab. To gain the same result without Colab, I need to copy their codes from the notebook and now it becomes the place where violation occur.

Alternatively, you can modify the notebook instead yourself.

In **Setup section**, append the following code before `end_time`.

```python
print(subprocess.run(['pip', 'uninstall', 'torch', 'torchvision', 'torchaudio'], stdout=subprocess.PIPE).stdout.decode('utf-8'));
print(subprocess.run(['pip', 'install', '--pre', 'torch==1.13.0.dev20220922', 'torchvision==0.14.0.dev20220924', '-f', 'https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html', '--no-deps'], stdout=subprocess.PIPE).stdout.decode('utf-8'));
```

And at the **Run section**, prepend the following code before any.

```python
%env PYTORCH_ENABLE_MPS_FALLBACK=1
```

The essence of using M1 as stable diffusion runner is installing a proper pytorch version supports M1. There is no magic.

**Comment by seia-soto** [comment]
As you know, you don't need to run Nvidia stuff in the notebook. Question can be made but I am not Python developer, so the answer can be incorrect.
