### ISSUE TITLE
RuntimeError: Placeholder storage has not been allocated on MPS device!

### ISSUE THREAD

**Issue by JT-Apps** [seia-soto/stable-diffusion-webui-m1#2]
I believe your script has this same issue (I cannot use "RESTORE FACES" in Auto WebUI without 'placeholder storage errors.) Please consider updating your script with this https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1708#issuecomment-1268460272 as well as https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1708#issuecomment-1270079228

**Comment by seia-soto** [comment]
I'll try to give another option. Before the update, you can fix the arguments manually at this time.

**Comment by seia-soto** [comment]
@jet3004 Did you test if `--use-cpu GFPGAN CodeFormer` option works on your end? The comment you mentioned is not the permanent solution (maximizing the performance) to this error and there is no cause to update, since the second comment you mentioned is already applied from the first commit of this repo. Please, confirm your result before posting.

**Comment by twopiearr** [comment]
The fix I've found is to add the `--use-cpu GFPGAN CodeFormer` flag to the launch command in this script, which is on line 218.

**Comment by seia-soto** [comment]
Nice to see. May I ask you what will be the better option? The first one is manually adding the parameter and the second one is using environment variable to append custom arguments.

**Comment by twopiearr** [comment]
Sorry - not really a coder. I know just enough to bumble my way through the solution above.

**Comment by seia-soto** [comment]
I shipped with an update. Now the custom arguments are fully supported for both invokeai and webui. You can just append arguments to run with custom parameters: `./script.sh -s --precision full --no-half --opt-split-attention-v1 --use-cpu GFPGAN CodeFormer`

Also, the default parameters applied.

https://github.com/seia-soto/stable-diffusion-webui-m1#steps

**Comment by seia-soto** [comment]
To check the custom arguments applied, see the console: `[[ WARN ]] Custom arguments detected: --precision full --no-half --opt-split-attention-v1 --use-cpu GFPGAN CodeFormer`.
